1. Import All Packages.

In [1]:
import pickle                                                                          # save the models
import pandas as pd                                                                    # pandas structuted package
import numpy as np                                                                     # numpy number package
import xgboost as xgb                                                                  # xgboost packages
from sklearn.preprocessing import StandardScaler                                       # data preprocessing 
from sklearn.preprocessing import LabelEncoder                                         # Label encoder 
from sklearn.model_selection import train_test_split                                   # split 80% train data, 20% test data                                
from sklearn.linear_model import LogisticRegression                                    # Classifier 1 st models
from sklearn.ensemble import RandomForestClassifier                                    # Classifier 2 nd models
from sklearn.tree import DecisionTreeClassifier                                        # Classifier 3 rd models
from xgboost  import XGBClassifier                                                     # Classifier 4 th models
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report    # check model errors and accuracy  
print("All Required Package are Imported")

All Required Package are Imported


2. Load Data sets.

In [3]:
df = pd.read_csv("C:/Users/saran/Desktop/EMI Predictions/EMI Datasets/EMI Prediction Clean.csv")
df.head(2)

Age  Gender Marital Status     Education  Monthly Salary Employment Type  \
0  38.0  Female        Married  Professional         82600.0         Private   
1  38.0  Female        Married      Graduate         21500.0         Private   

   Years Of Employment Company Type House Type  Monthly Rent  ...  \
0                  0.9     Mid Size     Rented       20000.0  ...   
1                  7.0          MNC     Family           0.0  ...   

   Existing Loans  Current Emi Amount  Credit Score  Bank Balance  \
0             Yes             23700.0         660.0      303200.0   
1             Yes              4100.0         714.0       92500.0   

   Emergency Fund             Emi Scenario  Requested Amount Requested Tenure  \
0         70200.0        Personal Loan EMI          850000.0               15   
1         26900.0  E-commerce Shopping EMI          128000.0               19   

   Emi Eligibility  Max Monthly Emi  
0     Not Eligible            500.0  
1     Not Eligible            700.0  

[2 rows x 27 columns]

In [4]:
df.columns

Index(['Age', 'Gender', 'Marital Status', 'Education', 'Monthly Salary',
       'Employment Type', 'Years Of Employment', 'Company Type', 'House Type',
       'Monthly Rent', 'Family Size', 'Dependents', 'School Fees',
       'College Fees', 'Travel Expenses', 'Groceries Utilities',
       'Other Monthly Expenses', 'Existing Loans', 'Current Emi Amount',
       'Credit Score', 'Bank Balance', 'Emergency Fund', 'Emi Scenario',
       'Requested Amount', 'Requested Tenure', 'Emi Eligibility',
       'Max Monthly Emi'],
      dtype='object')

3. Remove Outerlines in datasets.

In [5]:
Q1 = df['Max Monthly Emi'].quantile(0.25)
Q3 = df['Max Monthly Emi'].quantile(0.75)
IQR = Q3 - Q1

df_clean = df[~((df['Max Monthly Emi'] < (Q1 - 1.5*IQR)) | (df['Max Monthly Emi'] > (Q3 + 1.5*IQR)))]
print(df_clean.shape)

(387532, 27)


4. Change the categorical columns in to Label encoder.

In [25]:
categorical_cols = ['Gender', 'Marital Status', 'Education', 
                    'Employment Type', 'Company Type', 'House Type', 
                    'Emi Scenario','Existing Loans', 'Emi Eligibility']

numeric_cols = ['Age', 'Monthly Salary', 'Years Of Employment', 'Monthly Rent', 
                'Family Size', 'Dependents', 'School Fees', 'College Fees', 
                'Travel Expenses', 'Groceries Utilities', 'Other Monthly Expenses', 
                'Existing Loans', 'Current Emi Amount', 'Credit Score', 'Bank Balance', 
                'Emergency Fund', 'Requested Amount', 'Requested Tenure', 'Max Monthly Emi']
 

In [26]:
X_encoded = pd.get_dummies(df_clean[numeric_cols + categorical_cols], 
                           columns=categorical_cols, drop_first=True)

In [ ]:

le = LabelEncoder()


for col in categorical_cols:
    df_clean[col] = le.fit_transform(df_clean[col])

print(df)

In [27]:
X_encoded.columns

Index(['Age', 'Monthly Salary', 'Years Of Employment', 'Monthly Rent',
       'Family Size', 'Dependents', 'School Fees', 'College Fees',
       'Travel Expenses', 'Groceries Utilities', 'Other Monthly Expenses',
       'Current Emi Amount', 'Credit Score', 'Bank Balance', 'Emergency Fund',
       'Requested Amount', 'Requested Tenure', 'Max Monthly Emi',
       'Gender_Male', 'Marital Status_Single', 'Education_High School',
       'Education_Post Graduate', 'Education_Professional',
       'Employment Type_Private', 'Employment Type_Self-employed',
       'Company Type_MNC', 'Company Type_Mid Size', 'Company Type_Small',
       'Company Type_Startup', 'House Type_Own', 'House Type_Rented',
       'Emi Scenario_Education EMI', 'Emi Scenario_Home Appliances EMI',
       'Emi Scenario_Personal Loan EMI', 'Emi Scenario_Vehicle EMI',
       'Existing Loans_Yes', 'Existing Loans_Yes', 'Emi Eligibility_High Risk',
       'Emi Eligibility_Not Eligible'],
      dtype='object')

5. Split X and Y.

In [28]:
X = X_encoded.drop(['Emi Eligibility_High Risk', 'Emi Eligibility_Not Eligible'], axis=1)
y = df_clean['Emi Eligibility']  

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

6.  Split Train 80 % and Test 20 %, Model Selection.

# Random Forest Classifier.

In [29]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = RandomForestClassifier(random_state=42)

7. Model Train, Predictions

In [30]:
model.fit(x_train, y_train)
y_predict = model.predict(x_test)

8. Model Accuracy.

In [31]:
acc = accuracy_score(y_test, y_predict)
report = classification_report(y_test, y_predict)
cm = confusion_matrix(y_test, y_predict)


print(f"Accuracy Score: {acc:.4f}")
print("\nClassification Report:\n", report)
print("\nConfusion Matrix:\n", cm)


Accuracy Score: 0.9538

Classification Report:
               precision    recall  f1-score   support

    Eligible       0.92      0.96      0.94     18247
   High Risk       0.87      0.06      0.12      4846
Not Eligible       0.96      1.00      0.98     93167

    accuracy                           0.95    116260
   macro avg       0.92      0.67      0.68    116260
weighted avg       0.95      0.95      0.94    116260


Confusion Matrix:
 [[17513    40   694]
 [ 1465   300  3081]
 [   83     6 93078]]


9. Actual vs Predict.

In [32]:
prediction = pd.DataFrame({
    'Actual' : y_test.values,
    'Predict' : y_predict
})

prediction.iloc[15:30]

Actual       Predict
15  Not Eligible  Not Eligible
16  Not Eligible  Not Eligible
17  Not Eligible  Not Eligible
18  Not Eligible  Not Eligible
19  Not Eligible  Not Eligible
20  Not Eligible  Not Eligible
21  Not Eligible  Not Eligible
22      Eligible      Eligible
23      Eligible      Eligible
24  Not Eligible  Not Eligible
25  Not Eligible  Not Eligible
26  Not Eligible  Not Eligible
27     High Risk      Eligible
28  Not Eligible  Not Eligible
29  Not Eligible  Not Eligible

# Decision Tree Classifier.

1. Remove Outerlines.

In [33]:
Q1 = df['Max Monthly Emi'].quantile(0.25)
Q3 = df['Max Monthly Emi'].quantile(0.75)
IQR = Q3 - Q1

df_clean = df[~((df['Max Monthly Emi'] < (Q1 - 1.5*IQR)) | (df['Max Monthly Emi'] > (Q3 + 1.5*IQR)))]
print(df_clean.shape)

(387532, 27)


2. Inintial Categorical and Numerical Data.

In [34]:
categorical_cols = ['Gender', 'Marital Status', 'Education', 
                    'Employment Type', 'Company Type', 'House Type', 
                    'Emi Scenario','Existing Loans', 'Emi Eligibility']

numeric_cols = ['Age', 'Monthly Salary', 'Years Of Employment', 'Monthly Rent', 
                'Family Size', 'Dependents', 'School Fees', 'College Fees', 
                'Travel Expenses', 'Groceries Utilities', 'Other Monthly Expenses', 
                'Existing Loans', 'Current Emi Amount', 'Credit Score', 'Bank Balance', 
                'Emergency Fund', 'Requested Amount', 'Requested Tenure', 'Max Monthly Emi']

In [35]:
X_encoded = pd.get_dummies(df_clean[numeric_cols + categorical_cols], 
                           columns=categorical_cols, drop_first=True)

In [36]:
X_encoded.columns

Index(['Age', 'Monthly Salary', 'Years Of Employment', 'Monthly Rent',
       'Family Size', 'Dependents', 'School Fees', 'College Fees',
       'Travel Expenses', 'Groceries Utilities', 'Other Monthly Expenses',
       'Current Emi Amount', 'Credit Score', 'Bank Balance', 'Emergency Fund',
       'Requested Amount', 'Requested Tenure', 'Max Monthly Emi',
       'Gender_Male', 'Marital Status_Single', 'Education_High School',
       'Education_Post Graduate', 'Education_Professional',
       'Employment Type_Private', 'Employment Type_Self-employed',
       'Company Type_MNC', 'Company Type_Mid Size', 'Company Type_Small',
       'Company Type_Startup', 'House Type_Own', 'House Type_Rented',
       'Emi Scenario_Education EMI', 'Emi Scenario_Home Appliances EMI',
       'Emi Scenario_Personal Loan EMI', 'Emi Scenario_Vehicle EMI',
       'Existing Loans_Yes', 'Existing Loans_Yes', 'Emi Eligibility_High Risk',
       'Emi Eligibility_Not Eligible'],
      dtype='object')

3. Split X and Y.

In [17]:
X = X_encoded.drop(['Emi Eligibility_High Risk', 'Emi Eligibility_Not Eligible'], axis=1)
y = df_clean['Emi Eligibility']  



In [18]:
X

Age  Monthly Salary  Years Of Employment  Monthly Rent  Family Size  \
0       38.0         82600.0                  0.9       20000.0            3   
1       38.0         21500.0                  7.0           0.0            2   
3       58.0         66800.0                  2.2           0.0            5   
4       48.0         57300.0                  3.4           0.0            4   
5       38.0         38800.0                  5.0       13500.0            4   
...      ...             ...                  ...           ...          ...   
404795  27.0         32400.0                  5.0       10400.0            4   
404796  38.0         49200.0                  1.9           0.0            5   
404797  32.0         25700.0                  3.2        6300.0            1   
404798  48.0         47200.0                  3.0           0.0            4   
404799  38.0         34900.0                  1.2           0.0            2   

        Dependents  School Fees  College Fees  Travel Expenses  \
0                2          0.0           0.0           7200.0   
1                1       5100.0           0.0           1400.0   
3                4      11400.0           0.0           6200.0   
4                3       9400.0       21300.0           3600.0   
5                3          0.0       24100.0           3400.0   
...            ...          ...           ...              ...   
404795           3       2800.0        7000.0           2200.0   
404796           4      14000.0           0.0           2600.0   
404797           0          0.0           0.0           2000.0   
404798           3          0.0           0.0           7000.0   
404799           1          0.0           0.0           4800.0   

        Groceries Utilities  ...  Company Type_Small  Company Type_Startup  \
0                   19500.0  ...               False                 False   
1                    5400.0  ...               False                 False   
3                   11900.0  ...               False                 False   
4                   16200.0  ...               False                 False   
5                    8200.0  ...               False                 False   
...                     ...  ...                 ...                   ...   
404795               4900.0  ...               False                 False   
404796              13600.0  ...               False                 False   
404797               4600.0  ...               False                 False   
404798               8900.0  ...               False                 False   
404799               8100.0  ...               False                 False   

        House Type_Own  House Type_Rented  Emi Scenario_Education EMI  \
0                False               True                       False   
1                False              False                       False   
3                 True              False                       False   
4                False              False                       False   
5                False               True                       False   
...                ...                ...                         ...   
404795           False               True                       False   
404796            True              False                       False   
404797           False               True                       False   
404798            True              False                       False   
404799           False              False                       False   

        Emi Scenario_Home Appliances EMI  Emi Scenario_Personal Loan EMI  \
0                                  False                            True   
1                                  False                           False   
3                                  False                           False   
4                                   True                           False   
5                                  False                     

4. Split Train 80 % and Test 20 %, Model Ininitalized.

In [37]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = DecisionTreeClassifier(random_state=42)

5. Model Train and Predict.

In [38]:
model.fit(x_train, y_train)
y_predict = model.predict(x_test)

6. Model Accuracys.

In [39]:
acc = accuracy_score(y_test, y_predict)
reports = classification_report(y_test, y_predict)
cms = confusion_matrix(y_test, y_predict)

print(f"Accuracy Score: {acc:.4f}")
print("\nClassification Report:\n", reports)
print("\nConfusion Matrix:\n", cms)


Accuracy Score: 0.9754

Classification Report:
               precision    recall  f1-score   support

    Eligible       0.96      0.96      0.96     18247
   High Risk       0.71      0.72      0.71      4846
Not Eligible       0.99      0.99      0.99     93167

    accuracy                           0.98    116260
   macro avg       0.89      0.89      0.89    116260
weighted avg       0.98      0.98      0.98    116260


Confusion Matrix:
 [[17542   679    26]
 [  640  3467   739]
 [   18   754 92395]]


7. Check Actual VS Predict.

In [40]:
predic_dec = pd.DataFrame({
    'Actual' : y_test.values,
    'Predict' : y_predict
})

predic_dec.iloc[15:30]

Actual       Predict
15  Not Eligible  Not Eligible
16  Not Eligible  Not Eligible
17  Not Eligible  Not Eligible
18  Not Eligible  Not Eligible
19  Not Eligible  Not Eligible
20  Not Eligible  Not Eligible
21  Not Eligible  Not Eligible
22      Eligible      Eligible
23      Eligible      Eligible
24  Not Eligible  Not Eligible
25  Not Eligible  Not Eligible
26  Not Eligible  Not Eligible
27     High Risk      Eligible
28  Not Eligible  Not Eligible
29  Not Eligible  Not Eligible

In [44]:
with open("EMI Classifier Model.pkl", "wb") as file:
    pickle.dump(model, file)

print("✅ Model saved ")

✅ Model saved 


# XGBClassifier 

In [13]:
df_xgb = pd.read_csv("C:/Users/saran/Desktop/EMI Predictions/EMI Datasets/EMI Prediction Clean.csv")

1. Remove Outerlines.

In [14]:
Q1 = df_xgb['Max Monthly Emi'].quantile(0.25)
Q3 = df_xgb['Max Monthly Emi'].quantile(0.75)
IQR = Q3 - Q1

df_clean_x = df_xgb[~((df_xgb['Max Monthly Emi'] < (Q1 - 1.5*IQR)) | (df_xgb['Max Monthly Emi'] > (Q3 + 1.5*IQR)))]
print(df_clean_x.shape)

(387532, 27)


2. Split Categorical and Numerical Columns

In [5]:
numeric_cols = ['Age', 'Monthly Salary', 'Years Of Employment', 'Monthly Rent', 
                'Family Size', 'Dependents', 'School Fees', 'College Fees', 
                'Travel Expenses', 'Groceries Utilities', 'Other Monthly Expenses', 
                'Current Emi Amount', 'Credit Score', 'Bank Balance', 
                'Emergency Fund', 'Requested Amount', 'Requested Tenure', 
                'Max Monthly Emi']

categorical_cols = ['Gender', 'Marital Status', 'Education', 
                    'Employment Type', 'Company Type', 'House Type', 
                    'Emi Scenario','Existing Loans']

In [25]:
categorical_cols = ['Gender', 'Marital Status', 'Education', 
                    'Employment Type', 'Company Type', 'House Type', 
                    'Emi Scenario','Existing Loans', 'Emi Eligibility']


le = LabelEncoder()


for col in categorical_cols:
    df_clean_x[col] = le.fit_transform(df_clean_x[col])

print(df_clean_x)

C:\Users\saran\AppData\Local\Temp\ipykernel_18288\471259508.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_x[col] = le.fit_transform(df_clean_x[col])
C:\Users\saran\AppData\Local\Temp\ipykernel_18288\471259508.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_x[col] = le.fit_transform(df_clean_x[col])
C:\Users\saran\AppData\Local\Temp\ipykernel_18288\471259508.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_inde

         Age  Gender  Marital Status  Education  Monthly Salary  \
0       38.0       0               0          3         82600.0   
1       38.0       0               0          0         21500.0   
3       58.0       0               0          1         66800.0   
4       48.0       0               0          3         57300.0   
5       38.0       1               0          1         38800.0   
...      ...     ...             ...        ...             ...   
404795  27.0       1               0          0         32400.0   
404796  38.0       1               0          2         49200.0   
404797  32.0       1               1          0         25700.0   
404798  48.0       1               0          0         47200.0   
404799  38.0       0               0          0         34900.0   

        Employment Type  Years Of Employment  Company Type  House Type  \
0                     1                  0.9             2           2   
1                     1                  7.0   

In [16]:
X_encoded = pd.get_dummies(df_clean_x[numeric_cols + categorical_cols], 
                   columns=categorical_cols, drop_first=True)


3. Split X and Y.

In [26]:
X = df_clean_x.drop('Emi Eligibility', axis=1)
y = df_clean_x['Emi Eligibility']  


4. Split Train 80 % and Test 20 % , Model Initialize. 

In [27]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

5. Model Train and Prediction.

In [28]:
model.fit(x_train, y_train)
y_predict = model.predict(x_test)


c:\Users\saran\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [11:20:19] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


6. Model Accuracy.

In [29]:
acc_xgb = accuracy_score(y_test, y_predict)
reports_xgb = classification_report(y_test, y_predict)
cms_xgb = confusion_matrix(y_test, y_predict)

print(f"Accuracy Score: {acc_xgb:.4f}")
print("\nClassification Report:\n", reports_xgb)
print("\nConfusion Matrix:\n", cms_xgb)



Accuracy Score: 0.9897

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.98     18247
           1       0.90      0.85      0.87      4846
           2       1.00      1.00      1.00     93167

    accuracy                           0.99    116260
   macro avg       0.96      0.94      0.95    116260
weighted avg       0.99      0.99      0.99    116260


Confusion Matrix:
 [[17999   245     3]
 [  319  4099   428]
 [    0   197 92970]]


In [32]:
prediction_xgb = pd.DataFrame({
    'Actual' : y_test.values,
    'Predict' : y_predict
})

prediction_xgb.iloc[20:40]

Actual  Predict
20       2        2
21       2        2
22       0        0
23       0        0
24       2        2
25       2        2
26       2        2
27       1        1
28       2        2
29       2        2
30       2        2
31       2        2
32       2        2
33       2        2
34       2        2
35       2        2
36       0        0
37       2        2
38       2        2
39       2        2

# LogisticRegression.

1. Read CSV Files

In [50]:
df_logistic = pd.read_csv("C:/Users/saran/Desktop/EMI Predictions/EMI Datasets/EMI Prediction Clean.csv")
df_logistic.head(2)

Age  Gender Marital Status     Education  Monthly Salary Employment Type  \
0  38.0  Female        Married  Professional         82600.0         Private   
1  38.0  Female        Married      Graduate         21500.0         Private   

   Years Of Employment Company Type House Type  Monthly Rent  ...  \
0                  0.9     Mid Size     Rented       20000.0  ...   
1                  7.0          MNC     Family           0.0  ...   

   Existing Loans  Current Emi Amount  Credit Score  Bank Balance  \
0             Yes             23700.0         660.0      303200.0   
1             Yes              4100.0         714.0       92500.0   

   Emergency Fund             Emi Scenario  Requested Amount Requested Tenure  \
0         70200.0        Personal Loan EMI          850000.0               15   
1         26900.0  E-commerce Shopping EMI          128000.0               19   

   Emi Eligibility  Max Monthly Emi  
0     Not Eligible            500.0  
1     Not Eligible            700.0  

[2 rows x 27 columns]

2. Remove Oterlayers.

In [51]:
Q1 = df_logistic['Max Monthly Emi'].quantile(0.25)
Q3 = df_logistic['Max Monthly Emi'].quantile(0.75)
IQR = Q3 - Q1

df_clean_logistic = df_logistic[~((df_logistic['Max Monthly Emi'] < (Q1 - 1.5*IQR)) | (df_logistic['Max Monthly Emi'] > (Q3 + 1.5*IQR)))]
print(df_clean_logistic.shape)

(387532, 27)


3. Split Categorical and Numerical Columns.

In [52]:
categorical_cols = ['Gender', 'Marital Status', 'Education', 
                    'Employment Type', 'Company Type', 'House Type', 
                    'Emi Scenario','Existing Loans']

numeric_cols = ['Age', 'Monthly Salary', 'Years Of Employment', 'Monthly Rent', 
                'Family Size', 'Dependents', 'School Fees', 'College Fees', 
                'Travel Expenses', 'Groceries Utilities', 'Other Monthly Expenses', 
                 'Current Emi Amount', 'Credit Score', 'Bank Balance', 
                'Emergency Fund', 'Requested Amount', 'Requested Tenure', 'Max Monthly Emi']
 

In [53]:
categorical_cols = ['Gender', 'Marital Status', 'Education', 
                    'Employment Type', 'Company Type', 'House Type', 
                    'Emi Scenario','Existing Loans']


le = LabelEncoder()


for col in categorical_cols:
    df_clean_logistic[col] = le.fit_transform(df_clean_logistic[col])

print(df_clean_logistic)



C:\Users\saran\AppData\Local\Temp\ipykernel_18288\2946720159.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_logistic[col] = le.fit_transform(df_clean_logistic[col])
C:\Users\saran\AppData\Local\Temp\ipykernel_18288\2946720159.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_logistic[col] = le.fit_transform(df_clean_logistic[col])
C:\Users\saran\AppData\Local\Temp\ipykernel_18288\2946720159.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Dat

         Age  Gender  Marital Status  Education  Monthly Salary  \
0       38.0       0               0          3         82600.0   
1       38.0       0               0          0         21500.0   
3       58.0       0               0          1         66800.0   
4       48.0       0               0          3         57300.0   
5       38.0       1               0          1         38800.0   
...      ...     ...             ...        ...             ...   
404795  27.0       1               0          0         32400.0   
404796  38.0       1               0          2         49200.0   
404797  32.0       1               1          0         25700.0   
404798  48.0       1               0          0         47200.0   
404799  38.0       0               0          0         34900.0   

        Employment Type  Years Of Employment  Company Type  House Type  \
0                     1                  0.9             2           2   
1                     1                  7.0   

4. Split X and Y.

In [55]:
df_clean_logistic.columns

Index(['Age', 'Gender', 'Marital Status', 'Education', 'Monthly Salary',
       'Employment Type', 'Years Of Employment', 'Company Type', 'House Type',
       'Monthly Rent', 'Family Size', 'Dependents', 'School Fees',
       'College Fees', 'Travel Expenses', 'Groceries Utilities',
       'Other Monthly Expenses', 'Existing Loans', 'Current Emi Amount',
       'Credit Score', 'Bank Balance', 'Emergency Fund', 'Emi Scenario',
       'Requested Amount', 'Requested Tenure', 'Emi Eligibility',
       'Max Monthly Emi'],
      dtype='object')

5. Split X and Y.

In [59]:
X = df_clean_logistic.drop(['Emi Eligibility', 'Max Monthly Emi'], axis=1)
y = df_clean_logistic['Emi Eligibility']  


In [60]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

6. Model Selection Train & Predict.

In [85]:
model = LogisticRegression(multi_class= 'multinomial', penalty='l2')
model.fit(x_train, y_train)

predict = model.predict(x_test)


c:\Users\saran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\saran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


7. Model Accuracy.

In [86]:
acc = accuracy_score(y_test, predict)
reports= classification_report(y_test, predict)
cms = confusion_matrix(y_test, predict)

print(f"Accuracy Score: {acc:.2f}")
print("\nClassification Report:\n", reports)
print("\nConfusion Matrix:\n", cms)

c:\Users\saran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\saran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


Accuracy Score: 0.87

Classification Report:
               precision    recall  f1-score   support

    Eligible       0.67      0.64      0.66     18247
   High Risk       0.00      0.00      0.00      4846
Not Eligible       0.90      0.96      0.93     93167

    accuracy                           0.87    116260
   macro avg       0.52      0.53      0.53    116260
weighted avg       0.83      0.87      0.85    116260


Confusion Matrix:
 [[11640     0  6607]
 [ 1486     0  3360]
 [ 4162     0 89005]]


c:\Users\saran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


8. Check Actual VS Predict.

In [88]:
final_output = pd.DataFrame({
    'Actual' : y_test.values,
    'Predict' : predict
})

final_output.iloc[20:40]

Actual       Predict
20  Not Eligible  Not Eligible
21  Not Eligible  Not Eligible
22      Eligible  Not Eligible
23      Eligible      Eligible
24  Not Eligible  Not Eligible
25  Not Eligible  Not Eligible
26  Not Eligible  Not Eligible
27     High Risk  Not Eligible
28  Not Eligible  Not Eligible
29  Not Eligible  Not Eligible
30  Not Eligible  Not Eligible
31  Not Eligible  Not Eligible
32  Not Eligible  Not Eligible
33  Not Eligible  Not Eligible
34  Not Eligible  Not Eligible
35  Not Eligible  Not Eligible
36      Eligible      Eligible
37  Not Eligible  Not Eligible
38  Not Eligible  Not Eligible
39  Not Eligible  Not Eligible